packer {
  required_version = ">= 1.8.2"
}

variable "aws_region" {
  type    = string
  default = "us-east-1"
}

variable "consul_module_version" {
  type    = string
  default = "v0.7.4"
}

variable "consul_version" {
  type    = string
  default = "1.12.2"
}

variable "nomad_version" {
  type    = string
  default = "1.3.1"
}

data "amazon-ami" "autogenerated_1" {
  filters = {
    architecture        = "x86_64"
    name                = "*amzn2-ami-hvm-*"
    root-device-type    = "ebs"
    virtualization-type = "hvm"
  }
  most_recent = true
  owners      = ["amazon"]
  region      = "${var.aws_region}"
}

source "amazon-ebs" "amazon-linux-2-ami" {
  ami_description = "An Amazon Linux 2 AMI that has Nomad and Consul installed."
  ami_name        = "nomad-consul-amazon-linux-2"
  instance_type   = "t2.micro"
  region          = "${var.aws_region}"
  source_ami      = "${data.amazon-ami.autogenerated_1.id}"
  ssh_username    = "ec2-user"
}

build {
  sources = ["source.amazon-ebs.amazon-linux-2-ami"]

  provisioner "shell" {
    inline = ["sudo yum install -y git"]
    only   = ["amazon-linux-2-ami"]
  }
  
  provisioner "shell" {
    execute_command = "sudo {{ .Path }} --version ${var.nomad_version}"
    script = "install-nomad"
  }

}
